spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clc?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=info-mysql&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false
    # 你的数据库账户
    username:
    # 你的数据库密码
    password:
  redis:
    host: localhost
  clound:
    stream:
      bindings:
        public-notice:
          destination: info_notice
        handle-public-notice:
          destination: info_notice
  rabbitmq:
    host: localhost
    port: 5672
      # 你的rabbitmq账户
      username:
      # 你的rabbitmq密码
      password:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    discovery-client-enabled: false
    sender:
      type: web
    service:
      name: ${spring.application.name}
    compression:
      enabled: true
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled-by-default: true
feign:
  client:
    config:
      default:
        connect-timeout: 500
        read-timeout: 500
info:
  cache:
    account-token: 'token:'
    account-name: 'cache:account-name:'