server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clc?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=notice-mysql&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false
    # 你的数据库账户
    username:
    # 你的数据库密码
    password:
  cloud:
    stream:
      bindings:
        conditionChange:
          destination: condition-account-update
        publishObserve:
          destination: condition-account-update
          group: publish-notice-observe
        publishAccount:
          destination: notice-account-update
          group: publish-notice-account
  redis:
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    # 你的rabbitmq账户
    username:
    # 你的rabbitmq密码
    password:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    discovery-client-enabled: false
    sender:
      type: web
    service:
      name: ${spring.application.name}
    compression:
      enabled: true
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
feign:
  client:
    config:
      default:
        connect-timeout: 500
        read-timeout: 500
notice:
  save-path: 'web/public/upload/'
  uri-path: '/upload/'
  todo-link-url: '/notice/%d/todo'
  condition:
    accounts-map:
      0: 'localhost:8081/account/condition/%s/accounts'
      1: 'localhost:8081/notice/organization/condition/%s/accounts'
      2: 'localhost:8081/todo/condition/%s/accounts'
      3: 'localhost:8081/info/condition/%s/accounts'
    publish-map:
      0: 'localhost:8081/account/condition/%s/publish'
      1: 'localhost:8081/notice/organization/condition/%s/publish'
      2: 'localhost:8081/todo/condition/%s/publish'
      3: 'localhost:8081/info/condition/%s/publish'
  redis:
    condition: 'condition:organization:'
    publish-notice: 'publish:'
    account-token: 'token:'
    cache:
      notice: 'cache:notice:'
      account-name: 'cache:account-name:'
      organization-name: 'cache:organization-name:'
      tags: 'cache:tags:'
      collect-name: 'cache:info:ref:name:'
