server:
  port: 0
spring:
  rabbitmq:
    host: localhost
    port: 5672
    # 你的rabbitmq账户
    username:
    # 你的rabbitmq密码
    password:
  cloud:
    stream:
      bindings:
        publishNotice:
          destination: publish-notice
          group: search
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    discovery-client-enabled: false
    sender:
      type: web
    service:
      name: ${spring.application.name}
    compression:
      enabled: true
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
search:
  page-size: 20
