spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clc
# 你的数据库账户
    username:
# 你的数据库密码
    password:
  cache:
    type: redis
    cache-names: notice
    redis:
      time-to-live: 10000
      cache-null-values: false
  redis:
    host: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled-by-default: true
feign:
  client:
    config:
      default:
        connect-timeout: 500
        read-timeout: 500