spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clc
# 你的数据库账户
    username:
# 你的数据库密码
    password:
  redis:
    host: localhost
  clound:
    stream:
      bindings:
        public-notice:
          destination: public_notice
        handle-public-notice:
          destination: public_notice
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled-by-default: true
feign:
  client:
    config:
      default:
        connect-timeout: 500
        read-timeout: 500
notice:
  publish-notice: 'publish:'
  notice-file-path: 'web/public/upload/'
  web-file-path: '/upload/'
  account-token: 'token:'
  cache:
    notice: 'cache:notice:'
    account-name: 'cache:account-name:'
    organization-name: 'cache:organization-name:'
    tags: 'cache:tags'