spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clc
# 你的数据库账户
    username:
# 你的数据库密码
    password:
  redis:
    host: localhost
  clound:
    stream:
      bindings:
        public-todo:
          destination: public_todo
        handle-todo:
          destination: public_todo
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled-by-default: true
feign:
  client:
    config:
      default:
        connect-timeout: 500
        read-timeout: 500
todo:
  cache:
    account-token: 'token:'
    account-name: 'cache:account-name:'
    organization-name: 'cache:organization-name:'
    todo: 'cache:source-todo:'