package campuslifecenter.usercenter.mapper;

import campuslifecenter.usercenter.entry.Account;
import campuslifecenter.usercenter.entry.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    long countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Delete({
        "delete from account",
        "where sign_id = #{signId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Insert({
        "insert into account (sign_id, name, ",
        "password, gender, ",
        "create_data, security_key)",
        "values (#{signId,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{gender,jdbcType=TINYINT}, ",
        "#{createData,jdbcType=TIMESTAMP}, #{securityKey,jdbcType=VARCHAR})"
    })
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    List<Account> selectByExampleWithRowbounds(AccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Select({
        "select",
        "sign_id, name, password, gender, create_data, security_key",
        "from account",
        "where sign_id = #{signId,jdbcType=VARCHAR}"
    })
    @ResultMap("campuslifecenter.usercenter.mapper.AccountMapper.BaseResultMap")
    Account selectByPrimaryKey(String signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Update({
        "update account",
        "set name = #{name,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=TINYINT},",
          "create_data = #{createData,jdbcType=TIMESTAMP},",
          "security_key = #{securityKey,jdbcType=VARCHAR}",
        "where sign_id = #{signId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Account record);
}