package campuslifecenter.usercenter.mapper;

import campuslifecenter.usercenter.entry.AccountOrganization;
import campuslifecenter.usercenter.entry.AccountOrganizationExample;
import campuslifecenter.usercenter.entry.AccountOrganizationKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface AccountOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    long countByExample(AccountOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int deleteByExample(AccountOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Delete({
        "delete from account_organization",
        "where aid = #{aid,jdbcType=VARCHAR}",
          "and oid = #{oid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(AccountOrganizationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Insert({
        "insert into account_organization (aid, oid, ",
        "role)",
        "values (#{aid,jdbcType=VARCHAR}, #{oid,jdbcType=INTEGER}, ",
        "#{role,jdbcType=TINYINT})"
    })
    int insert(AccountOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int insertSelective(AccountOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    List<AccountOrganization> selectByExampleWithRowbounds(AccountOrganizationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    List<AccountOrganization> selectByExample(AccountOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Select({
        "select",
        "aid, oid, role",
        "from account_organization",
        "where aid = #{aid,jdbcType=VARCHAR}",
          "and oid = #{oid,jdbcType=INTEGER}"
    })
    @ResultMap("campuslifecenter.usercenter.mapper.AccountOrganizationMapper.BaseResultMap")
    AccountOrganization selectByPrimaryKey(AccountOrganizationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") AccountOrganization record, @Param("example") AccountOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByExample(@Param("record") AccountOrganization record, @Param("example") AccountOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByPrimaryKeySelective(AccountOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Update({
        "update account_organization",
        "set role = #{role,jdbcType=TINYINT}",
        "where aid = #{aid,jdbcType=VARCHAR}",
          "and oid = #{oid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AccountOrganization record);
}