package campuslifecenter.usercenter.mapper;

import campuslifecenter.usercenter.entry.RolePermissionExample;
import campuslifecenter.usercenter.entry.RolePermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    long countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Delete({
        "delete from role_permission",
        "where oid = #{oid,jdbcType=INTEGER}",
          "and rid = #{rid,jdbcType=INTEGER}",
          "and pid = #{pid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Insert({
        "insert into role_permission (oid, rid, ",
        "pid)",
        "values (#{oid,jdbcType=INTEGER}, #{rid,jdbcType=INTEGER}, ",
        "#{pid,jdbcType=INTEGER})"
    })
    int insert(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int insertSelective(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    List<RolePermissionKey> selectByExampleWithRowbounds(RolePermissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    List<RolePermissionKey> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") RolePermissionKey record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByExample(@Param("record") RolePermissionKey record, @Param("example") RolePermissionExample example);
}