package campuslifecenter.usercenter.mapper;

import campuslifecenter.usercenter.entry.SecurityLogExample;
import campuslifecenter.usercenter.entry.SecurityLogKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SecurityLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    long countByExample(SecurityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int deleteByExample(SecurityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Delete({
        "delete from securityLog",
        "where aid = #{aid,jdbcType=VARCHAR}",
          "and input_time = #{inputTime,jdbcType=TIMESTAMP}"
    })
    int deleteByPrimaryKey(SecurityLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Insert({
        "insert into securityLog (aid, input_time)",
        "values (#{aid,jdbcType=VARCHAR}, #{inputTime,jdbcType=TIMESTAMP})"
    })
    int insert(SecurityLogKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int insertSelective(SecurityLogKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    List<SecurityLogKey> selectByExampleWithRowbounds(SecurityLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    List<SecurityLogKey> selectByExample(SecurityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecurityLogKey record, @Param("example") SecurityLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByExample(@Param("record") SecurityLogKey record, @Param("example") SecurityLogExample example);
}