package campuslifecenter.usercenter.mapper;

import campuslifecenter.usercenter.entry.SignInLog;
import campuslifecenter.usercenter.entry.SignInLogExample;
import campuslifecenter.usercenter.entry.SignInLogKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface SignInLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    long countByExample(SignInLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int deleteByExample(SignInLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Delete({
        "delete from signInLog",
        "where aid = #{aid,jdbcType=VARCHAR}",
          "and sign_in_time = #{signInTime,jdbcType=TIMESTAMP}"
    })
    int deleteByPrimaryKey(SignInLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Insert({
        "insert into signInLog (aid, sign_in_time, ",
        "sign_out_time, ip, ",
        "source, type, cookie)",
        "values (#{aid,jdbcType=VARCHAR}, #{signInTime,jdbcType=TIMESTAMP}, ",
        "#{signOutTime,jdbcType=TIMESTAMP}, #{ip,jdbcType=VARCHAR}, ",
        "#{source,jdbcType=TINYINT}, #{type,jdbcType=TINYINT}, #{cookie,jdbcType=VARCHAR})"
    })
    int insert(SignInLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int insertSelective(SignInLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    List<SignInLog> selectByExampleWithRowbounds(SignInLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    List<SignInLog> selectByExample(SignInLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Select({
        "select",
        "aid, sign_in_time, sign_out_time, ip, source, type, cookie",
        "from signInLog",
        "where aid = #{aid,jdbcType=VARCHAR}",
          "and sign_in_time = #{signInTime,jdbcType=TIMESTAMP}"
    })
    @ResultMap("campuslifecenter.usercenter.mapper.SignInLogMapper.BaseResultMap")
    SignInLog selectByPrimaryKey(SignInLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") SignInLog record, @Param("example") SignInLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByExample(@Param("record") SignInLog record, @Param("example") SignInLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    int updateByPrimaryKeySelective(SignInLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Update({
        "update signInLog",
        "set sign_out_time = #{signOutTime,jdbcType=TIMESTAMP},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "source = #{source,jdbcType=TINYINT},",
          "type = #{type,jdbcType=TINYINT},",
          "cookie = #{cookie,jdbcType=VARCHAR}",
        "where aid = #{aid,jdbcType=VARCHAR}",
          "and sign_in_time = #{signInTime,jdbcType=TIMESTAMP}"
    })
    int updateByPrimaryKey(SignInLog record);
}