package campuslifecenter.usercenter.entry;

import java.io.Serializable;
import java.util.Date;

public class Account implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sign_id
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String signId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.gender
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_data
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Date createData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.security_key
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String securityKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.sign_id
     *
     * @return the value of account.sign_id
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Account withSignId(String signId) {
        this.setSignId(signId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.sign_id
     *
     * @param signId the value for account.sign_id
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setSignId(String signId) {
        this.signId = signId == null ? null : signId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name
     *
     * @return the value of account.name
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Account withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name
     *
     * @param name the value for account.name
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Account withPassword(String password) {
        this.setPassword(password);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.gender
     *
     * @return the value of account.gender
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Account withGender(Byte gender) {
        this.setGender(gender);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.gender
     *
     * @param gender the value for account.gender
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_data
     *
     * @return the value of account.create_data
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Date getCreateData() {
        return createData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Account withCreateData(Date createData) {
        this.setCreateData(createData);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_data
     *
     * @param createData the value for account.create_data
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setCreateData(Date createData) {
        this.createData = createData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.security_key
     *
     * @return the value of account.security_key
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getSecurityKey() {
        return securityKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Account withSecurityKey(String securityKey) {
        this.setSecurityKey(securityKey);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.security_key
     *
     * @param securityKey the value for account.security_key
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setSecurityKey(String securityKey) {
        this.securityKey = securityKey == null ? null : securityKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", signId=").append(signId);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", gender=").append(gender);
        sb.append(", createData=").append(createData);
        sb.append(", securityKey=").append(securityKey);
        sb.append("]");
        return sb.toString();
    }
}