package campuslifecenter.usercenter.entry;

import java.io.Serializable;

public class AccountOrganizationKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_organization.aid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_organization.oid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_organization.aid
     *
     * @return the value of account_organization.aid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public AccountOrganizationKey withAid(String aid) {
        this.setAid(aid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_organization.aid
     *
     * @param aid the value for account_organization.aid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setAid(String aid) {
        this.aid = aid == null ? null : aid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_organization.oid
     *
     * @return the value of account_organization.oid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public AccountOrganizationKey withOid(Integer oid) {
        this.setOid(oid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_organization.oid
     *
     * @param oid the value for account_organization.oid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", aid=").append(aid);
        sb.append(", oid=").append(oid);
        sb.append("]");
        return sb.toString();
    }
}