package campuslifecenter.usercenter.entry;

import java.io.Serializable;
import java.util.Date;

public class Organization implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.id
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.creator
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.name
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.visibility
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Byte visibility;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.create_data
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Date createData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.id
     *
     * @return the value of organization.id
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Organization withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.id
     *
     * @param id the value for organization.id
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.creator
     *
     * @return the value of organization.creator
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Organization withCreator(String creator) {
        this.setCreator(creator);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.creator
     *
     * @param creator the value for organization.creator
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.name
     *
     * @return the value of organization.name
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Organization withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.name
     *
     * @param name the value for organization.name
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.visibility
     *
     * @return the value of organization.visibility
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Byte getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Organization withVisibility(Byte visibility) {
        this.setVisibility(visibility);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.visibility
     *
     * @param visibility the value for organization.visibility
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setVisibility(Byte visibility) {
        this.visibility = visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.create_data
     *
     * @return the value of organization.create_data
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Date getCreateData() {
        return createData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Organization withCreateData(Date createData) {
        this.setCreateData(createData);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.create_data
     *
     * @param createData the value for organization.create_data
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setCreateData(Date createData) {
        this.createData = createData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", creator=").append(creator);
        sb.append(", name=").append(name);
        sb.append(", visibility=").append(visibility);
        sb.append(", createData=").append(createData);
        sb.append("]");
        return sb.toString();
    }
}