package campuslifecenter.usercenter.entry;

import java.io.Serializable;

public class RolePermissionKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.oid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.rid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.pid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.oid
     *
     * @return the value of role_permission.oid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public RolePermissionKey withOid(Integer oid) {
        this.setOid(oid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.oid
     *
     * @param oid the value for role_permission.oid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.rid
     *
     * @return the value of role_permission.rid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public RolePermissionKey withRid(Integer rid) {
        this.setRid(rid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.rid
     *
     * @param rid the value for role_permission.rid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.pid
     *
     * @return the value of role_permission.pid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public RolePermissionKey withPid(Integer pid) {
        this.setPid(pid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.pid
     *
     * @param pid the value for role_permission.pid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oid=").append(oid);
        sb.append(", rid=").append(rid);
        sb.append(", pid=").append(pid);
        sb.append("]");
        return sb.toString();
    }
}