package campuslifecenter.usercenter.entry;

import java.io.Serializable;
import java.util.Date;

public class SecurityLogKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column securityLog.aid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column securityLog.input_time
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Date inputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column securityLog.aid
     *
     * @return the value of securityLog.aid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public SecurityLogKey withAid(String aid) {
        this.setAid(aid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column securityLog.aid
     *
     * @param aid the value for securityLog.aid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setAid(String aid) {
        this.aid = aid == null ? null : aid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column securityLog.input_time
     *
     * @return the value of securityLog.input_time
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public SecurityLogKey withInputTime(Date inputTime) {
        this.setInputTime(inputTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column securityLog.input_time
     *
     * @param inputTime the value for securityLog.input_time
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", aid=").append(aid);
        sb.append(", inputTime=").append(inputTime);
        sb.append("]");
        return sb.toString();
    }
}