package campuslifecenter.usercenter.entry;

import java.io.Serializable;
import java.util.Date;

public class SignInLogKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signInLog.aid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signInLog.sign_in_time
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Date signInTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signInLog.aid
     *
     * @return the value of signInLog.aid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public SignInLogKey withAid(String aid) {
        this.setAid(aid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signInLog.aid
     *
     * @param aid the value for signInLog.aid
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setAid(String aid) {
        this.aid = aid == null ? null : aid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signInLog.sign_in_time
     *
     * @return the value of signInLog.sign_in_time
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Date getSignInTime() {
        return signInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public SignInLogKey withSignInTime(Date signInTime) {
        this.setSignInTime(signInTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signInLog.sign_in_time
     *
     * @param signInTime the value for signInLog.sign_in_time
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setSignInTime(Date signInTime) {
        this.signInTime = signInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", aid=").append(aid);
        sb.append(", signInTime=").append(signInTime);
        sb.append("]");
        return sb.toString();
    }
}