package campuslifecenter.usercenter.entry;

import java.io.Serializable;
import java.util.Date;

public class SignInLog extends SignInLogKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signInLog.sign_out_time
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Date signOutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signInLog.ip
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signInLog.source
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Byte source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signInLog.type
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signInLog.cookie
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private String cookie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signInLog.sign_out_time
     *
     * @return the value of signInLog.sign_out_time
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Date getSignOutTime() {
        return signOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public SignInLog withSignOutTime(Date signOutTime) {
        this.setSignOutTime(signOutTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signInLog.sign_out_time
     *
     * @param signOutTime the value for signInLog.sign_out_time
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setSignOutTime(Date signOutTime) {
        this.signOutTime = signOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signInLog.ip
     *
     * @return the value of signInLog.ip
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public SignInLog withIp(String ip) {
        this.setIp(ip);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signInLog.ip
     *
     * @param ip the value for signInLog.ip
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signInLog.source
     *
     * @return the value of signInLog.source
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public SignInLog withSource(Byte source) {
        this.setSource(source);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signInLog.source
     *
     * @param source the value for signInLog.source
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signInLog.type
     *
     * @return the value of signInLog.type
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public SignInLog withType(Byte type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signInLog.type
     *
     * @param type the value for signInLog.type
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signInLog.cookie
     *
     * @return the value of signInLog.cookie
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public String getCookie() {
        return cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public SignInLog withCookie(String cookie) {
        this.setCookie(cookie);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signInLog.cookie
     *
     * @param cookie the value for signInLog.cookie
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    public void setCookie(String cookie) {
        this.cookie = cookie == null ? null : cookie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signInLog
     *
     * @mbg.generated Wed Nov 25 15:44:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", signOutTime=").append(signOutTime);
        sb.append(", ip=").append(ip);
        sb.append(", source=").append(source);
        sb.append(", type=").append(type);
        sb.append(", cookie=").append(cookie);
        sb.append("]");
        return sb.toString();
    }
}